name: Python Web Application CI

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-flask flask Werkzeug
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Check code formatting
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
        FLASK_ENV: testing
        FLASK_DEBUG: 0
        HOST: 127.0.0.1
      run: |
        pytest tests/ -v --disable-warnings

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run security checks
      env:
        FLASK_ENV: production
        FLASK_DEBUG: 0
        HOST: 127.0.0.1
      run: |
        bandit -r . -x ./tests,./venv -ll -ii
        safety check